# Generated by Django 2.2.14 on 2020-12-09 10:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleantablename', models.TextField(default='')),
                ('industrytablename', models.TextField(default='')),
                ('mvpmsg', models.TextField(default='')),
                ('mgpmsg', models.TextField(default='')),
                ('mvimsg', models.TextField(default='')),
                ('mgimsg', models.TextField(default='')),
                ('dirpath', models.TextField(default='')),
                ('status', models.CharField(max_length=2)),
                ('exceptionmsgs', models.TextField(default='')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updatetime')),
            ],
        ),
        migrations.CreateModel(
            name='LoadDataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default=None)),
                ('dirpath', models.TextField(default=None)),
                ('exceptionmsgs', models.TextField(default='')),
                ('status', models.CharField(max_length=2)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updatetime')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.TextField(default='')),
                ('resourceid', models.TextField(default='')),
                ('resourcename', models.TextField(default='')),
                ('resourceurl', models.TextField(default='')),
                ('resourceparentid', models.TextField(default='')),
                ('resourceparentname', models.TextField(default='')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.TextField(default='')),
                ('rolename', models.TextField(default='')),
                ('usermobile', models.TextField(default='')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('usermobile', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('realname', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('is_active', models.TextField(default='')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updatetime')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
